sudo: required
git:
  depth: 3

language: node_js
node_js:
  - "10"


install:
  - git fetch --tags

  - npm install ./ppx-sedlex
  - npm install --ignore-scripts
  - if [ $COMPONENT = runtime ]; then npm install bs-platform; fi

  - if [ $COMPONENT = ppx ]; then wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-ocaml.sh; fi
  - if [ $COMPONENT = ppx ]; then bash -ex .travis-ocaml.sh; fi
  - if [ $COMPONENT = ppx ]; then opam pin -y -n add sedlex .; fi
  - if [ $COMPONENT = ppx ]; then opam install -y --deps-only sedlex; fi
  - if [ $COMPONENT = ppx ]; then eval `opam config env`; fi
  - if [ $COMPONENT = ppx ]; then opam config env; opam list; fi

script: npm run build:$COMPONENT

jobs:
  include:
    - stage: deploy
      os: linux
      script: npm run prepare:ppx
      deploy: &gh-release
        provider: releases
        skip_cleanup: true
        api_key:
          secure: W+hmJYg7+pCybW+xWSHNnDIrJ0a02VDaDw4qP5Jh7YP9v5hmrTDU0V5ZvSnlLgUvR2a1nn1GJnEsuDhJKqhqWLrVjGHs/fNzVrvZQjdCkEHSsQUlzm0LByBqMI5qxEa2GnUZesAyai+J6J4mrkAQfgHOMgtaOAMkcG2InpSy6ZG+QQmX/hVE/8tD2OU1abhgxmcHVCmPA8JT/GZhFe8OP+dMEI/ZC2Z+ru6mQ10oYjM/2ah3OuagjLY0i2z9Kpr0hR3naq9Ve4AGvosKK8kDuyK4Hsj6MgjFd9DZWsJW1iGVhaUgMEIPHy+TDW2CXTa7kjJ5qaGPBh3Mn9Cy/qCoGgTMspn/ldFyTOJSVERyo5ccA/S/QJLqtpkHZ1X2Xh5WF2b5l2mpAU9jHqLbJSfqavB8mS5AApvuVl+ahhJ8+4zsd9BgTpb7L0938Yky3LHndmMcXY6j79hvLoe3mfQHZrckP4KsnsVyD0b6dcSXLOfOO3sVQhJHstlkDTPQxuEqLGxuxMHW1UdLvDr0gJXncET3/mxitHjCwCEYSDTCffE54zGPSlHZP7Nd63N+lMMR7HZCE7GCDx0UzC9aKz4Ta3qOCZffByrh9wRcG50nXvFV/dt3OAPEebI9HfymmwqoulTHpSsg52AfgyEp75AORpdZeTtJW3JffXHf7gPT/H8=
        file_glob: true
        file: dist/*
        on:
          tags: true
    - os: osx
      script: npm run prepare:ppx
      deploy: *gh-release

env:
  global:
    - OCAML_VERSION=4.02
    - OPAM_SWITCH=4.02.3+buckle-master
  matrix:
    - COMPONENT=ppx
    - COMPONENT=runtime
    - COMPONENT=examples
os:
  - linux
  - osx
