sudo: required
git:
  depth: 3

language: node_js
node_js:
  - "10"

install:
  - if [ $COMPONENT = ppx ]; then wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-ocaml.sh; fi
  - if [ $COMPONENT = ppx ]; then bash -ex .travis-ocaml.sh; fi
  - if [ $COMPONENT = ppx ]; then opam pin -y -n add sedlex .; fi
  - if [ $COMPONENT = ppx ]; then opam install -y --deps-only sedlex; fi
  - if [ $COMPONENT = ppx ]; then eval `opam config env`; fi
  - if [ $COMPONENT = ppx ]; then opam config env; opam list; fi

  - if [ $COMPONENT = runtime ]; then npm ci --ignore-scripts; fi
  - if [ $COMPONENT = runtime ]; then npm install bs-platform; fi

script: npm run build:$COMPONENT

jobs:
  fast_finish: true
  allow_failures:
    - os: osx
      env: COMPONENT=ppx
  include:
    - stage: deploy
      script: npm run build:ppx
      deploy:
        provider: releases
        skip_cleanup: true
        api_key:
          secure: "Q/U06wd3L8jCN3gZ4mW4rd4LgPO1SdBCG/RLmrgCW5rt7FydO0rIbhGKiYWveyLMgcQEfLIitpTBhwDeVaj+mIHlXl4r81z3TxM9wleoujvJ+9xBN9UBlTbNN1toggsNHzaMJbqLUaGEgUOYE4bLM4/o9xgOAL9YJVgH/j8cfe2oBTq2rb+F2IZ7srI9iXatlxm6EHnLeXm64rhmNxagHLEC/q/OkOe9nNtpFuWVuaXkTuLtq8O0L0za5psGlNjZxdz1jqY7AnD2k1z0VVqKHOc3dZEBf65Yl8ln60ZTV+nqGRZBayKFMb3JPIJFE5rLEQ7QqGoVPNQ7p6ukx3rVHAJ6ObMdvY6IIhE5YjdC8u19Bdry8jUi3siJcqVRDogkAx5CQK6waqMOduma/PoPbmijrFUJEqEJ+l62meUbEp75HUTlqen132+deDZWFqKHfqkQGYNlwo0TLKH0NExUQy9t127k+hv/VyYWh0tkiUjf7TmikcoCYOhc6ChMxfFMAkRYz+DMcanq6bI0WLEEQVrCNmdSvznd+9ZNKNUSYsYO27pX5SFmCtJKACtzFlp4ZgjlXZArabqP7qFLa0F1G3I2k3JJ3XE6rUuosvnNkf9RafvV2LCRibmDT9AFtQO0KU1C5RUGofo2m02vXwMKJEnx46A3xZepeROXNkes0OY="
        file_glob: true
        file: dist/*
        on:
          tags: true

env:
  global:
    - OCAML_VERSION=4.02
    - OPAM_SWITCH=4.02.3+buckle-master
  matrix:
    - COMPONENT=ppx
    - COMPONENT=runtime
os:
  - linux
  - osx
